### ISSUE TITLE
Regression: latest 3.10.3 (3.10.3+sha.78c31f6) fails to compile on ESP32-C6-DevKit-1 but 3.10.3 works

### ISSUE THREAD

**Issue by lorbx** [FastLED/FastLED#2133]
I'm using PlatformIO and the ESP32-C6-DevKit-1 board with Arduino environment.  In my platformio.ini file, if I set lib_deps to "FastLED" or "FastLED=https://github.com/FastLED/FastLED", platformio downloads version "3.10.3+sha.78c31f6" and even the very simplest possible FastLED application fails to compile.  I'm using WS2812B.  If I force version to be "3.10.3" using lib_deps "fastLED/FastLED@3.10.3" it compiles fine.

The compiler error is:

.pio/libdeps/esp32-c6-devkitc-1/FastLED/src/platforms/esp/32/drivers/rmt/rmt_5/rmt5_worker.cpp: In function 'void rmt5_nmi_buffer_refill()':
.pio/libdeps/esp32-c6-devkitc-1/FastLED/src/platforms/esp/32/drivers/rmt/rmt_5/rmt5_worker.cpp:134:25: error: 'void fl::RmtWorker::fillNextHalf()' is private within this context
  134 |     worker->fillNextHalf();
      |     ~~~~~~~~~~~~~~~~~~~~^~
In file included from .pio/libdeps/esp32-c6-devkitc-1/FastLED/src/platforms/esp/32/drivers/rmt/rmt_5/rmt5_worker.cpp:8:
.pio/libdeps/esp32-c6-devkitc-1/FastLED/src/platforms/esp/32/drivers/rmt/rmt_5/rmt5_worker.h:144:20: note: declared private here
  144 |     void IRAM_ATTR fillNextHalf();
      |                    ^~~~~~~~~~~~
*** [.pio/build/esp32-c6-devkitc-1/lib451/FastLED/platforms/esp/32/drivers/rmt/rmt_5/rmt5_worker.cpp.o] Error 1

My platformio.ini:
[env:esp32-c6-devkitc-1]
platform = espressif32
board = esp32-c6-devkitc-1
framework = arduino
lib_deps =
    ;fastLED/FastLED@3.10.3   ;compiles!
    ;FastLED     ;breaks!
    FastLED=https://github.com/FastLED/FastLED   ;breaks!

My test code:
#include <Arduino.h>
#include <FastLED.h>

void setup() {
    CRGB leds[10];
    FastLED.addLeds<WS2812B,GPIO_NUM_20,GRB>(leds, 10).setCorrection(TypicalLEDStrip);
    for(int i = 0; i < 10; i++) leds[i] = CRGB::Red;
    FastLED.show();
}

**Comment by zackees** [comment]
please upgrade and let me know if it works.

master branch has a new RMT5 worker pool that allows you to render more strips than workers, just like RMT4 had
