### PR TITLE
fix(tests): exclude tests/fbuild_qemu_smoke from host test discovery (linux_native regression from #2594)

### LINKED ISSUE #2599: linux_native red after #2594: meson test discovery picks up tests/fbuild_qemu_smoke/src/main.cpp
## Symptom

`linux_native` host C++ tests fail on master since #2594 merged:

```
tests/fbuild_qemu_smoke/src/main.cpp:19:10: fatal error: 'Arduino.h' file not found
FAILED: tests/main.so.p/fbuild_qemu_smoke_src_main.cpp.o
```

Reproducible: most recent `linux_native` workflow on master (run 26688913311).

## Root cause

#2594 renamed `tests/fbuild_qemu_smoke/src/main.ino` → `main.cpp` to satisfy `arduino-lint-action`'s rule LD003 ("Sketch(es) found outside examples and extras folders"). That fixed `Arduino Library Lint`, but meson's test-file discovery (`tests/discover_tests.py` → `tests/test_config.py::EXCLUDED_TEST_DIRS`) walks `tests/` looking for `.cpp` files — the `.ino` was invisible to that walker. After the rename, meson tries to compile `main.cpp` as a host unit test against the native toolchain, which doesn't have `<Arduino.h>`.

The fixture is intentionally a **standalone PIO project** (driven by `ci/tests/test_fbuild_qemu.py` via `pio run`), not a host unit test. It must not be picked up by `linux_native`.

## Fix

One-line addition to `tests/test_config.py::EXCLUDED_TEST_DIRS`:

```python
TESTS_DIR / "fbuild_qemu_smoke",
```

with an explanatory comment crossing this back to #2593 / #2594. The fixture continues to be driven correctly by `ci/tests/test_fbuild_qemu.py`.

## Test plan

- [x] `bash lint` clean.
- [x] `bash test fastled_core --cpp --clean` — host smoke test compiles + passes (35 s clean, includes a full meson reconfigure that re-runs discovery).
- [ ] CI: `linux_native` workflow should go green again.
- [ ] `ci/tests/test_fbuild_qemu.py` continues to work (path-based).

## Notes

This is a regression my own #2594 introduced — apologies for the churn. The two cleanup options were (a) exclude the fixture from meson's walk (this PR), or (b) move it out of `tests/` entirely. (a) is one line and preserves the existing file layout that `test_fbuild_qemu.py` already knows.

---

Filed during a coordinated CI-green sweep; fix PR landing immediately.

### PR DESCRIPTION
**Pull request by zackees**
## Summary

- `linux_native` host tests have been red since #2594 merged. The rename of `tests/fbuild_qemu_smoke/src/main.ino` → `main.cpp` satisfied arduino-lint's LD003, but it also exposed the file to the host test discovery (which walks for `.cpp`, not `.ino`).
- The host toolchain has no `<Arduino.h>`, so `main.cpp:19` fatal-errors out at the first include.
- The fixture is intentionally a standalone PlatformIO project (driven by `ci/tests/test_fbuild_qemu.py` via `pio run`), not a host unit test.
- One-line fix: add `TESTS_DIR / "fbuild_qemu_smoke"` to `EXCLUDED_TEST_DIRS` in `tests/test_config.py`.

## Test plan

- [x] `bash lint` clean.
- [x] `bash test fastled_core --cpp --clean` — host smoke test compiles + passes (full reconfigure verifies discovery skip).
- [ ] CI: `linux_native` workflow should turn green again.
- [ ] `ci/tests/test_fbuild_qemu.py` continues to drive the fixture via the unchanged path.

Fixes #2599

## Notes

Regression my own #2594 introduced — apologies for the churn. Two cleanup options were (a) exclude the fixture from discovery (this PR, one line) or (b) move it out of `tests/` entirely (larger blast radius, breaks the test runner's path). Going with (a).

Generated with Claude Code (https://claude.com/claude-code)

## Summary by CodeRabbit

* **Tests**
  * Excluded a standalone test directory from recursive discovery to avoid native test compilation issues.
  * Test discovery now includes additional source file extensions so more test sources are found.
  * Test metadata caching and change-detection broadened to account for those sources and improved robustness of cache handling and CLI messages.

* **Style**
  * Updated type annotations and formatting for consistency across test tooling.

[Review Change Stack](https://app.coderabbit.ai/change-stack/FastLED/FastLED/pull/2600?utm_source=github_walkthrough&utm_medium=github&utm_campaign=change_stack)

### CODE REVIEW

**Comment by zackees** [comment]
## Second opinion + extension

The one-line directory exclusion **is correct** for the immediate regression — host discovery walks `*.cpp`, the rename in #2594 exposed `main.cpp`, excluding the dir restores green. The thread-the-needle alternative (rename back to `.ino` and skip discovery via extension) would re-break arduino-lint LD003.

The deeper inconsistency is that **the host test discovery was the only walker treating `.ino` as a non-sibling extension**:

| Walker | Walks |
|--------|-------|
| `ci/early_exit_cache.py` (`CPP_EXTS`) | `.cpp`, `.h`, `.hpp`, `.c`, `.ino` |
| `ci/meson/cache_utils.py` (`_SOURCE_EXTS`) | `.cpp`, `.h`, `.hpp`, `.c`, `.ino` |
| `ci/fix_has_include.py` (`FILE_PATTERNS`) | `.h`, `.hpp`, `.cpp`, `.ino` |
| `ci/cpp_lint_cache.py` | `examples/**/*.ino` + cpp |
| `ci/fingerprint/rules.py` | `examples/**/*.ino` |
| Multiple `ci/meson/discover_examples*.py` | `*.ino` |
| `ci/lint/stage_impls.py` | handles `.ino` explicitly |
| **`tests/discover_tests.py`** (before this PR) | `.cpp` only ❌ |
| **`tests/test_metadata_cache.py`** (before this PR) | `.cpp` only ❌ |

Pushed `921c5a1a` on top — extracts `TEST_SOURCE_GLOBS = ("*.cpp", "*.ino")` in `discover_tests.py`, and `test_metadata_cache.py` imports the same constant. Behavior is unchanged today (no `.ino` test files exist; the one historical fixture is inside the directory this PR already excludes), but a future `.ino` rename / fixture won't slip past discovery the same way #2594 did.

`bash lint` green; `uv run python tests/discover_tests.py tests | wc -l` still returns the same 225 test files, and the excluded fixture is not in the output.

Note: `test_metadata_cache.py` got incidental ruff-format hygiene (single→double quotes, `List`→`list`, etc.) — flagged in the commit body. Logical change is ~6 lines.
