### ISSUE TITLE
Compilation error with Teensy 4.0

### ISSUE THREAD

**Issue by pierrotm777** [FastLED/FastLED#2086]
Hello,

I have this error when i try to compile with your 3.10.2 and 3.10.3 version.
So, i continue to use your 3.10.1 version .

```

c:\tmp\Arduino_Compilateur\arduino-1.8.19\MyArduinoSketch\libraries\FastLED\src\platforms\shared\active_strip_data\active_strip_data.cpp: In member function 'fl::string fl::ActiveStripData::infoJsonString()':
c:\tmp\Arduino_Compilateur\arduino-1.8.19\MyArduinoSketch\libraries\FastLED\src\platforms\shared\active_strip_data\active_strip_data.cpp:81:22: error: expected unqualified-id before '[' token
     for (const auto &[stripIndex, stripData] : mStripMap) {
                      ^
c:\tmp\Arduino_Compilateur\arduino-1.8.19\MyArduinoSketch\libraries\FastLED\src\platforms\shared\active_strip_data\active_strip_data.cpp:81:22: error: expected ';' before '[' token
c:\tmp\Arduino_Compilateur\arduino-1.8.19\MyArduinoSketch\libraries\FastLED\src\platforms\shared\active_strip_data\active_strip_data.cpp:81:23: error: 'stripIndex' was not declared in this scope
     for (const auto &[stripIndex, stripData] : mStripMap) {
                       ^
c:\tmp\Arduino_Compilateur\arduino-1.8.19\MyArduinoSketch\libraries\FastLED\src\platforms\shared\active_strip_data\active_strip_data.cpp:81:35: error: 'stripData' was not declared in this scope
     for (const auto &[stripIndex, stripData] : mStripMap) {
                                   ^
c:\tmp\Arduino_Compilateur\arduino-1.8.19\MyArduinoSketch\libraries\FastLED\src\platforms\shared\active_strip_data\active_strip_data.cpp: In lambda function:
c:\tmp\Arduino_Compilateur\arduino-1.8.19\MyArduinoSketch\libraries\FastLED\src\platforms\shared\active_strip_data\active_strip_data.cpp:81:46: error: expected '{' before ':' token
     for (const auto &[stripIndex, stripData] : mStripMap) {
                                              ^
c:\tmp\Arduino_Compilateur\arduino-1.8.19\MyArduinoSketch\libraries\FastLED\src\platforms\shared\active_strip_data\active_strip_data.cpp: In member function 'fl::string fl::ActiveStripData::infoJsonString()':
c:\tmp\Arduino_Compilateur\arduino-1.8.19\MyArduinoSketch\libraries\FastLED\src\platforms\shared\active_strip_data\active_strip_data.cpp:81:46: error: expected ';' before ':' token
c:\tmp\Arduino_Compilateur\arduino-1.8.19\MyArduinoSketch\libraries\FastLED\src\platforms\shared\active_strip_data\active_strip_data.cpp:81:46: error: expected primary-expression before ':' token
c:\tmp\Arduino_Compilateur\arduino-1.8.19\MyArduinoSketch\libraries\FastLED\src\platforms\shared\active_strip_data\active_strip_data.cpp:81:46: error: expected ')' before ':' token
c:\tmp\Arduino_Compilateur\arduino-1.8.19\MyArduinoSketch\libraries\FastLED\src\platforms\shared\active_strip_data\active_strip_data.cpp:81:46: error: expected primary-expression before ':' token
c:\tmp\Arduino_Compilateur\arduino-1.8.19\MyArduinoSketch\libraries\FastLED\src\platforms\shared\active_strip_data\active_strip_data.cpp: In member function 'fl::string fl::ActiveStripData::infoJsonStringNew()':
c:\tmp\Arduino_Compilateur\arduino-1.8.19\MyArduinoSketch\libraries\FastLED\src\platforms\shared\active_strip_data\active_strip_data.cpp:116:22: error: expected unqualified-id before '[' token
     for (const auto &[stripIndex, stripData] : mStripMap) {
                      ^
c:\tmp\Arduino_Compilateur\arduino-1.8.19\MyArduinoSketch\libraries\FastLED\src\platforms\shared\active_strip_data\active_strip_data.cpp:116:22: error: expected ';' before '[' token
c:\tmp\Arduino_Compilateur\arduino-1.8.19\MyArduinoSketch\libraries\FastLED\src\platforms\shared\active_strip_data\active_strip_data.cpp:116:23: error: 'stripIndex' was not declared in this scope
     for (const auto &[stripIndex, stripData] : mStripMap) {
                       ^
c:\tmp\Arduino_Compilateur\arduino-1.8.19\MyArduinoSketch\libraries\FastLED\src\platforms\shared\active_strip_data\active_strip_data.cpp:116:35: error: 'stripData' was not declared in this scope
     for (const auto &[stripIndex, stripData] : mStripMap) {
                                   ^
c:\tmp\Arduino_Compilateur\arduino-1.8.19\MyArduinoSketch\libraries\FastLED\src\platforms\shared\active_strip_data\active_strip_data.cpp: In lambda function:
c:\tmp\Arduino_Compilateur\arduino-1.8.19\MyArduinoSketch\libraries\FastLED\src\platforms\shared\active_strip_data\active_strip_data.cpp:116:46: error: expected '{' before ':' token
     for (const auto &[stripIndex, stripData] : mStripMap) {
                                              ^
c:\tmp\Arduino_Compilateur\arduino-1.8.19\MyArduinoSketch\libraries\FastLED\src\platforms\shared\active_strip_data\active_strip_data.cpp: In member function 'fl::string fl::ActiveStripData::infoJsonStringNew()':
c:\tmp\Arduino_Compilateur\arduino-1.8.19\MyArduinoSketch\libraries\FastLED\src\platforms\shared\active_strip_data\active_strip_data.cpp:116:46: error: expected ';' before ':' token
c:\tmp\Arduino_Compilateur\arduino-1.8.19\MyArduinoSketch\libraries\FastLED\src\platforms\shared\active_strip_data\active_strip_data.cpp:116:46: error: expected primary-expression before ':' token
c:\tmp\Arduino_Compilateur\arduino-1.8.19\MyArduinoSketch\libraries\FastLED\src\platforms\shared\active_strip_data\active_strip_data.cpp:116:46: error: expected ')' before ':' token
c:\tmp\Arduino_Compilateur\arduino-1.8.19\MyArduinoSketch\libraries\FastLED\src\platforms\shared\active_strip_data\active_strip_data.cpp:116:46: error: expected primary-expression before ':


```

**Comment by zackees** [comment]
I see what's going on, this is a C++17 feature that's resulting in a compiler error with C++11 compiler.

When I downgraded the host compilation for the example test then this exact same error popped up. Luckily there are only a few places this shows up so the fix is easy.

**Comment by pierrotm777** [comment]
I use last Arduino ide V2.3.6.

**Comment by pierrotm777** [comment]
Ok, thank you for your fix 😉

**Comment by zackees** [comment]
c:\tmp\Arduino_Compilateur\arduino-1.8.19

shows you were using 1.8.19
