### ISSUE TITLE
chore(rp2350w): hand off final #3832 hardware validation

### ISSUE THREAD

**Issue by zackees** [FastLED/FastLED#3864]
## Context

The RP2350W source and deployment work is ready for final board validation, but the attached hardware is not currently usable for HIL.

- Parent bring-up: #3832
- Implementation PR: #3863 (`feat/rp2350w-btstack-transport`, head `33cf3d6524e85bfbd9653d92b9939dec19d7a4bc`)
- Required fbuild deployment hardening was merged in FastLED/fbuild#1263 (`2976d863`).
- Source validation on the implementation branch passed: targeted pytest (184 tests), `bash lint`, and `bash compile rp2350w --examples AutoResearch` using the local fbuild development executable.

The board scan last showed an RP2350-associated COM17 as `health=phantom selectable=no` (USB ID `2E8A:F00F`, serial `2DCB876B587EA334`). Windows also reported an unidentified device on a root port with Code 43; fbuild cannot safely associate that unidentified USB device with the phantom COM port. COM9 was a healthy ESP32-S3, not the required ESP32-C6 network peer.

A firmware watchdog can recover a running firmware stall, but cannot repair a failed/absent host USB enumeration. Do not use raw serial tools or direct flashers; deploy only through fbuild/autoresearch after the device is healthy and selectable.

## Handoff procedure

1. Re-establish the RP2350W as a healthy, selectable serial device (try a known-good data cable/root port and inspect the physical wiring, including the GPIO 0/1 test bridge). Confirm the real ESP32-C6 peer and port as well.
2. Run the following fbuild-backed HIL checks, substituting the confirmed C6 port:

```sh
bash autoresearch rp2350w --watchdog-soak --upload-port COM17 --timeout 120s
bash autoresearch rp2350w --flex-io --rp-pio-index 2 --tx-pin 0 --rx-pin 1 --upload-port COM17 --timeout 120s
bash autoresearch rp2350w --net-peer --upload-port COM17 --peer-environment esp32c6 --peer-upload-port <C6_PORT> --timeout 120s
bash autoresearch rp2350w --ble --upload-port COM17 --timeout 120s
bash autoresearch rp2350w --net-peer --ota --upload-port COM17 --peer-environment esp32c6 --peer-upload-port <C6_PORT> --timeout 360s
```

3. Record the complete HIL results on #3832 and PR #3863, including whether the watchdog-soak exercise recovers cleanly without a replug. Retest the PIO loopback with the 0/1 bridge only after confirming that wiring is intentional.

## Acceptance criteria

- [ ] RP2350W and ESP32-C6 appear healthy and selectable in `fbuild port scan`.
- [ ] All five HIL flows above pass through fbuild/autoresearch.
- [ ] The watchdog-soak run demonstrates automatic recovery from a firmware stall, with no board wedge or manual replug required.
- [ ] PIO2 GPIO 0/1 loopback has captured evidence and its physical bridge is documented.
- [ ] #3832 and PR #3863 contain the bench evidence; remaining PR review/CI items are separated from environment flakes before merge.
- [ ] Any follow-up preserves the project rule: no static data unless it is owned by `fl::singleton<T>` / `fl::Singleton<T>`.

## Related

- #3832
- #3863
- FastLED/fbuild#1263
- FastLED/fbuild#1265 (separate Teensy framework-library selection failure seen in CI)
- #3838 and #3775 (separate Teensy CI/link failures)

**Comment by zackees** [comment]
## Bench attempt — 2026-08-06, all five HIL flows blocked before reaching hardware

Attempted the handoff procedure on this repo at `feat/rp2350w-btstack-transport` (`33cf3d6`). Three independent blockers, two of them outside FastLED. **No HIL flow reached the device**, so no acceptance criteria can be checked off yet.

### Blocker 1 — the rp2350w build fails: required fbuild fix is merged but *unreleased* (primary blocker)

```
$ bash autoresearch rp2350w --watchdog-soak --upload-port COM17 --timeout 120s
...
BTstackLib/src/BTstackLib.cpp:
cores/rp2040/_needsbt.h:4:24: error: static assertion failed:
  This library needs Bluetooth enabled. Use the 'Tools->IP/Bluetooth Stack' menu ...
    4 | #define ENABLE_CLASSIC 0
pico-sdk/lib/btstack/src/ble/sm.h:229:1: error: 'irk_lookup_state_t' does not name a type
❌ Deploy failed (fbuild) [12.0s]
```

The generated `.build/pio/rp2350w/platformio.ini` is correct — it contains `board_build.ipbtstack = ipv4btcble` and `lib_deps = BTstackLib,HTTPUpdate`, exactly as `ci/boards.py` on this branch intends. The problem is that the installed fbuild ignores the menu selection:

| | |
|---|---|
| FastLED pins | `fbuild==2.5.14` (`pyproject.toml:189`) |
| `2.5.14` published | 2026-08-06 **05:08:05Z** |
| FastLED/fbuild#1263 `2976d863b` merged | 2026-08-06 **08:36:39Z** |
| Newest fbuild tag / newest PyPI release | **`v2.5.14`** |

`2976d863b` is `HEAD` of fbuild `main` but sits **after** the `v2.5.14` tag, and no release workflow has run since. So the Bluetooth-menu support that #3864 lists as a prerequisite exists only in fbuild `main` — there is no installable fbuild that honours `board_build.ipbtstack`, which is why `libipv4.a` is still linked and `ENABLE_CLASSIC`/`ENABLE_BLE` stay 0.

This matches the note in the issue that source validation passed "using the local fbuild development executable" — that path is not reproducible from a clean checkout.

**Needed: cut fbuild `v2.5.15` (or later) containing `2976d863b`, then bump the `fbuild==` pin here.** I have not pinned FastLED to a git SHA — fbuild ships as a Rust wheel and a source pin would force a Rust build in every CI job.

### Blocker 2 — COM17 is still an unhealthy Windows devnode (confirms the original report)

Verified independently of the BLE build by deploying the non-BLE `rp2350` profile, which builds cleanly and therefore reaches the deploy stage:

```
$ bash autoresearch rp2350 --upload-port COM17 --timeout 90s
deploy error: deploy failed: RP2040 runtime selector "COM17" matches COM17
  (health phantom; instance USB\VID_2E8A&PID_F00F\2DCB876B587EA334),
  which Windows reports as not usable; fbuild will not open or reset a stale
  devnode record — reconnect the board (or enter BOOTSEL) and retry
deploy target USB\VID_2E8A&PID_F00F\2DCB876B587EA334 is a known-unhealthy Windows devnode
❌ Deploy failed (fbuild) [207.9s]
```

So the board state is unchanged from the handoff report, and it is a *host enumeration* failure, not firmware. `fbuild port scan` still shows:

- `COM17 2E8A:F00F ser=2DCB876B587EA334 → health=phantom selectable=no`
- one `Unknown USB device: Windows problem code 43 at Port_#0014.Hub_#0001`
- **no ESP32-C6 present at all** — the only `health=healthy` port is `COM9`, an Espressif S3 (`8C:BF:EA:CF:87:B4`). The `--net-peer` and `--ota` flows cannot run until a real C6 is attached.

fbuild offers `--admin` for a scoped one-shot Windows PnP recovery under UAC. **I deliberately did not run it**: it needs interactive UAC, it mutates host PnP state, and it would not unblock anything while Blocker 1 stands. Recommend the physical path first (hold BOOT, tap RESET; known-good data cable; different root port) — consistent with the RP2040 case where software-only recovery was exhausted because a bus reset is not a VBUS cycle.

### Blocker 3 — GitHub Actions is in a major outage right now

PR #3863 cannot be re-validated and no new CI can be collected:

```
$ curl -s https://www.githubstatus.com/api/v2/components.json | ... Actions -> major_outage
$ gh workflow run qemu_esp32s3_test.yml --ref <branch>
could not create workflow dispatch event: HTTP 500
```

A freshly pushed PR (#3865) has **0** workflow runs against its head SHA. I have a watch armed for recovery.

### Separating PR #3863's red CI from environment flakes (acceptance criterion 5)

| Check | Verdict |
|---|---|
| `teensy41 / build` — `undefined reference to set_audioClock(int, long, unsigned long, bool)` | **Pre-existing, not caused by #3863.** The same failure occurs on `master` itself at `e1190d455` ([run 31084792473](https://github.com/FastLED/FastLED/actions/runs/31084792473)). Tracked by #3838 / #3775 / FastLED/fbuild#1265. `set_audioClock` is declared in the PJRC Audio library's `utility/imxrt_hw.h` but its translation unit is never linked — a framework-library selection problem, not a FastLED source problem. |
| `esp32s3_qemu_rmt / qemu_test` — exit 127 | **Environment gap, fixable here.** `qemu-system-xtensa: error while loading shared libraries: libslirp.so.0`. `.github/workflows/qemu_template.yml` installed `libsdl2-2.0-0` but not `libslirp0`. Fix opened as **#3865**. |
| Everything else on #3863 | green |

So #3863 has **no** genuine code-caused CI failure. It remains correctly un-merged only because its bench evidence does not exist yet.

### Status against the acceptance criteria

- [ ] RP2350W and ESP32-C6 healthy/selectable — **no**: COM17 phantom, no C6 attached at all
- [ ] Five HIL flows pass — **no**: none reached the device
- [ ] Watchdog-soak recovery demonstrated — **no**
- [ ] PIO2 GPIO 0/1 loopback evidence — **no**
- [x] PR CI items separated from environment flakes — **done**, table above; #3865 opened for the one fixable flake
- [x] No static data outside `fl::singleton<T>` / `fl::Singleton<T>` — `ble_rp.cpp.hpp` uses `fl::Singleton<RpBleRuntime>`, asserted by `ci/tests/test_rp2350w_board_config.py`

### To unblock, in order

1. Cut an fbuild release containing `2976d863b`, then bump `fbuild==` in `pyproject.toml`.
2. Physically recover the RP2350W (BOOTSEL + replug on a known-good data cable/port).
3. Attach a real ESP32-C6 for the `--net-peer` / `--ota` legs.
4. Re-run the five flows and post the transcripts here.

Nothing was faked and no workaround was committed: per the deployment rule I did not touch `picotool`/raw serial, and I did not pin fbuild to a git SHA to route around the missing release.

**Comment by zackees** [comment]
## Correction — the QEMU `libslirp` fix moved to fbuild

I previously listed **#3865** (adding `libslirp0` to `qemu_template.yml`) as the fix for the `esp32s3_qemu_rmt` exit-127 failure. **That PR is now closed unmerged** — the fix belongs in fbuild, which downloads, caches, extracts and invokes the QEMU binary. FastLED patching its workflow to install a shared library on fbuild's behalf would go stale on the next QEMU revision bump and would mask the real bug.

The asymmetry I flagged supports this: `esp32s3_qemu_lcd` passed while `esp32s3_qemu_rmt` failed in the same run on the same image — a missing distro package cannot explain that. It points at a raced/partial extract of the Espressif tarball's bundled `lib/libslirp.so.0` in fbuild's toolchain cache.

Now tracked as **FastLED/fbuild#1266**, which proposes atomic toolchain extraction (fixing the whole class) and having fbuild provision the QEMU runtime deps — the latter would also let us delete the pre-existing `libsdl2-2.0-0` workaround from `qemu_template.yml`.

The triage conclusion is unchanged: this check is an **environment/toolchain failure, not a code failure**, and PR #3863 still has no code-caused CI failure.

**Comment by zackees** [comment]
## Blocker 1 cleared — the rp2350w BLE build now works

Rebuilt fbuild from `main` (`0014f032`, version-bumped to **2.5.15**) and patched it into this repo's venv. The build that previously died at `_needsbt.h`'s `static_assert(ENABLE_CLASSIC, ...)` now completes:

```
$ bash compile rp2350w --examples AutoResearch
  508.13 Linking firmware.elf
  510.15 Building firmware.bin
  510.15 Flash: 1.12MB / 4.00MB (28.1%)
  510.15 RAM:   128.95KB / 512.00KB (25.2%)
build succeeded in 510.2s (flash: 1177936 bytes, ram: 132048 bytes)
SUCCESS: AutoResearch
```

So `board_build.ipbtstack = ipv4btcble` is now honoured, `libipv4-bt.a` is linked, and BTstackLib compiles. `ci/boards.py` on this branch was correct all along — the only thing missing was FastLED/fbuild#1263 reaching a consumable build.

## What the HIL flows now hit

With the build fixed, the flows get all the way to the deploy stage and stop on the hardware, exactly as characterised earlier:

```
$ bash autoresearch rp2350w --watchdog-soak --upload-port COM17 --timeout 120s
✅ All C++ lint checks passed
DEPLOYING (fbuild)
deploy error: deploy failed: RP2040 runtime selector "COM17" matches COM17
  (health phantom; instance USB\VID_2E8A&PID_F00F\2DCB876B587EA334),
  which Windows reports as not usable; fbuild will not open or reset a stale
  devnode record — reconnect the board (or enter BOOTSEL) and retry
❌ Deploy failed (fbuild) [392.6s]
```

That is a clean demarcation: **everything up to and including the build is green; only the physical board is in the way.**

## Remaining blockers

| # | Blocker | Status |
|---|---|---|
| 1 | fbuild lacking #1263 | ✅ **resolved** — fixed in fbuild `main`, verified end-to-end here |
| 2 | COM17 `health=phantom selectable=no` | ❌ still present (`2E8A:F00F`, `2DCB876B587EA334`), plus the Code 43 device on the root port. Host USB enumeration, not firmware — needs BOOTSEL + a known-good data cable/port. |
| 3 | No ESP32-C6 attached | ❌ still absent — only healthy port is COM9, an ESP32-S3. `--net-peer` and `--ota` cannot run. |

## Two follow-ups before this closes

1. **fbuild 2.5.15 is not published yet.** I am running a local build of `main`. `pyproject.toml` here still pins `fbuild==2.5.14`, so this is not yet reproducible from a clean checkout — the exact trap flagged earlier about "validated with the local fbuild development executable". Once 2.5.15 is on PyPI the pin needs bumping (tracked in FastLED/fbuild#1269).
2. Once the board and a C6 are attached, all five flows can run for real and this issue can be closed on evidence.

Unrelated but fixed along the way while working here: #3867 (stray `-r` file — root-caused to the ARM link inheriting the daemon's cwd, fixed in FastLED/fbuild#1268 and extended to every ARM linker in fbuild#1270) and #3868 (the `gh pr merge` review guard checking the wrong repo). A full 9-minute rp2350w build now leaves the working tree completely clean.

**Comment by zackees** [comment]
## Blocker 1 is now closed properly — fbuild 2.5.15 is on PyPI and pinned

fbuild **2.5.15** was published at 2026-08-07 05:34:16Z (tag `v2.5.15`). Confirmed all three needed commits are ancestors of the tag: `2976d863` (#1263, Arduino Bluetooth menu), `0dd68b24` (#1268) and `1324d6c6` (#1270).

The pin is bumped and merged as **#3871**.

Crucially this is now validated against the **published wheel**, not a local development executable — which was the flaw in this issue's original "source validation passed" claim:

```
$ bash compile rp2350w --examples AutoResearch
build succeeded in 253.7s (flash: 1177936 bytes, ram: 132048 bytes)
SUCCESS: AutoResearch
```

Byte-identical to the pre-release local build, working tree clean afterwards. **The RP2350W BLE build is now reproducible from a clean checkout.**

## Status against the acceptance criteria

| Blocker | |
|---|---|
| fbuild lacking #1263 | ✅ **resolved** — released, pinned, verified from a clean checkout |
| COM17 `health=phantom selectable=no` | ❌ unchanged (`2E8A:F00F`, `2DCB876B587EA334`) |
| No ESP32-C6 attached | ❌ unchanged — only healthy port is COM9, an ESP32-S3 |

So everything through the build is green, and the two remaining blockers are purely physical. Once the RP2350W re-enumerates (BOOTSEL + a known-good data cable/port) and a real C6 is attached, all five HIL flows can run and this can be closed on evidence.

Also fixed along the way and now in the pinned fbuild: the stray `-r` file (#3867) that dirtied the working tree on every clean build.

**Comment by zackees** [comment]
## Correction: the RP2350W is not wedged — it is not connected

I have been repeating this issue's premise that COM17 is an unhealthy/wedged devnode needing BOOTSEL or a scoped PnP recovery. That premise is wrong, and I should have checked Windows directly much earlier instead of trusting the `health=phantom` label.

### What Windows actually reports

```
> Get-PnpDevice -Class Ports | Select Status, Present, FriendlyName
Status   Present  FriendlyName
OK       True     USB Serial Device (COM9)          <- ESP32-S3, the only attached board
Unknown  False    USB Serial Device (COM17)         <- RP2350W
Unknown  False    USB Serial Device (COM12)         <- Mizu RP2040
Unknown  False    USB Serial Device (COM19/20/21/7) <- Teensys
Unknown  False    USB Serial Device (COM13/22/25)   <- other S3s
Unknown  False    Silicon Labs CP210x (COM11)
Unknown  False    USB Serial Device (COM10)         <- LPC-Link2
```

`Present = False`. In Windows terms a "phantom" devnode is a **leftover registry record for hardware that is not currently attached** — it is not a corrupted or wedged device. Every port fbuild listed as `health=phantom` is simply a board that is unplugged. That is also why nearly all of them showed as phantom at once: not a host-wide failure, just one attached board out of thirteen records.

### When the RP2350W was last seen

```
USB\VID_2E8A&PID_F00F\2DCB876B587EA334
  LocationInfo      Port_#0001.Hub_#0011
  Parent            USB\VID_05E3&PID_0610\7&3afc677d&0&1   (Genesys Logic hub)
  LastArrivalDate   2026-08-01 22:27:59
  LastRemovalDate   2026-08-01 22:41:50
```

Last attached **2026-08-01**, removed 14 minutes later, and not seen since. There is currently **no `VID_2E8A` device present on this host at all** — neither the RP2350W nor the Mizu RP2040.

The Genesys hub it was plugged into is present and healthy (`Status OK`), so the hub and the port are fine — there is just nothing plugged into them.

### The Code 43 device is a different board

```
USB\VID_0000&PID_0002\6&3AF0F9CE&0&14
  FriendlyName      Unknown USB Device (Device Descriptor Request Failed)
  Problem           CM_PROB_FAILED_POST_START
  LocationInfo      Port_#0014.Hub_#0001
  Parent            USB\ROOT_HUB30\5&4087d53&0&0
  FirstInstallDate  2026-03-11
```

Different port, different hub (a **direct root port**, not the Genesys hub), and first installed back in March. This is the long-standing RP2040 IM411 board that has been descriptor-failed on root hub `5&4087d53` since mid-July — a separate, already-known problem. It is **not** the RP2350W, and conflating the two is what produced the "board is wedged" reading.

### What this means for the handoff

- No software recovery is applicable. `--admin` scoped PnP recovery would have done nothing, because there is no present device to recover — I am glad I did not run it.
- BOOTSEL / `UF2=` is also moot until the board is physically attached.
- Step 1 of the handoff procedure is simply: **plug the RP2350W in.** Then re-scan; it should enumerate as `2E8A:F00F` serial `2DCB876B587EA334` and become selectable.
- Same for the ESP32-C6 — the only Espressif device present is `303A:1001` serial `8C:BF:EA:CF:87:B4`, the S3 on COM9. No C6 has been attached.

### Also worth fixing in the handoff commands

The five commands in the description all pass `--upload-port COM17`. That pins deploy to a specific (currently stale) record and bypasses fbuild's own fallback, which deliberately excludes unhealthy CDC records and continues via the BOOTSEL-volume path (FastLED/fbuild#1147). Dropping `--upload-port` gives a more accurate error and lets that fallback work. If the board ever does come up in BOOTSEL without a working CDC port, `--upload-port UF2=<volume>` flashes the UF2 directly.

### Unchanged

Blocker 1 remains resolved: fbuild 2.5.15 is released and pinned (#3871), and the rp2350w BLE build is verified reproducible from a clean checkout. The remaining work is purely "attach the hardware".

**Comment by zackees** [comment]
Handoff context for the next agent — including why `health=phantom` means *not attached* rather than *broken*, the hardware still needed here (RP2350W re-seat on a different cable/root port; a real ESP32-C6 has never been attached), and why the five commands above should drop `--upload-port COM17` — is written up in FastLED/fbuild#1282.

**Comment by zackees** [comment]
## Correction: the ESP32-C6 peer requirement is already satisfied

The issue states *"COM9 was a healthy ESP32-S3, not the required ESP32-C6 network peer."* That is wrong, and I repeated it myself earlier in this investigation before checking.

`303A:1001` is Espressif's generic USB-Serial-JTAG PID, shared across S3 / C3 / C6 — it does not identify the chip. Probing instead of reading the label:

```
$ detect_attached_chip("COM9")
ChipDetectionResult(ok=True, chip_type='ESP32-C6', environment='esp32c6', error_message=None)
```

COM9 is an **ESP32-C6**, healthy and selectable (the probe requires actual two-way communication, so this is not a registry artifact). The other three `303A:1001` records — COM13, COM22, COM25 — do not respond to esptool and are not usable peers.

So `--peer-environment esp32c6 --peer-upload-port COM9` is ready to use. No C6 needs to be sourced.

## Still blocked: the RP2350W itself

```
COM17     2E8A:F00F    ser=2DCB876B587EA334
          └─ Generic RP2350    health=phantom selectable=no

$ fbuild port doctor --port COM17
  presence   NOT PRESENT
  last seen  5d ago
  verdict    not attached — this is a stale registry record, not a fault
```

Last arrival 2026-08-01. This is not a wedged devnode or a Code 43 fault — the board has simply not been attached for six days. All five HIL flows require `--upload-port COM17`, so none can run until it is physically plugged in.

**Suggested next attempt:** a different data cable and a direct root port rather than the Genesys hub (`USB\VID_05E3&PID_0610\7&3AFC677D&0&1`) — an earlier replug produced no new device node at all, which points at cable or hub rather than the board.

## Note on the handoff commands

Drop `--upload-port COM17` from the RP2350W side of those five commands. It pins deploy to one CDC record and defeats fbuild's own protection, which excludes unhealthy records and falls back to the BOOTSEL volume (FastLED/fbuild#1147). Keep `--peer-upload-port COM9` for the C6, where an explicit port is correct.

## Related work landed

#3873 makes this failure mode legible: an explicitly named `--upload-port` that is not attached now aborts in seconds with "not attached, last seen 5d ago" instead of failing at deploy after ~7 minutes of build, with a stale `health=phantom` record that reads like a wedged board. That misreading is what cost this investigation its first pass.

Blocker 1 (the fbuild 2.5.15 pin carrying FastLED/fbuild#1263) was resolved and merged in #3871.
