### PR TITLE
Update component.mk to work with ESP-IDF 3.3.x

### PR DESCRIPTION
**Pull request by elliottkember**
I found, when updating FastLED to the latest `src` directory change, that I was getting a lot of errors about missing files!

I think this is due to the new `src` directory, which I think is a very good idea and cleans up the repository a lot. Seems as though `component.mk`'s list of paths is not searched recursively for files.

I also had to add `src/platforms/esp32` to the paths for the new clockless files to be found, otherwise I had a lot of these errors in the linker:

```
libmain.a(main.o):(.literal._ZN15SoulmateLibrary15lightPercentageEf[SoulmateLibrary::lightPercentage(float)]+0xc): undefined reference to `FastLED'
libmain.a(main.o):(.literal._ZN15SoulmateLibrary15lightPercentageEf[SoulmateLibrary::lightPercentage(float)]+0x10): undefined reference to `fill_solid(CRGB*, int, CRGB const&)'
libmain.a(main.o):(.literal._ZN15SoulmateLibrary15lightPercentageEf[SoulmateLibrary::lightPercentage(float)]+0x18): undefined reference to `CFastLED::show(unsigned char)'
libmain.a(main.o):(.literal._ZN15SoulmateLibrary18playCurrentRoutineEv[SoulmateLibrary::playCurrentRoutine()]+0x0): undefined reference to `hsv2rgb_rainbow(CHSV const&, CRGB&)'
libmain.a(main.o):(.literal._ZN15SoulmateLibrary10showPixelsEv[SoulmateLibrary::showPixels()]+0x1c): undefined reference to `blend(CRGB const&, CRGB const&, unsigned char)'
libmain.a(main.o):(.literal._ZN15SoulmateLibrary5setupEv[SoulmateLibrary::setup()]+0x24): undefined reference to `FastLED'
libmain.a(main.o):(.literal._ZN15SoulmateLibrary5setupEv[SoulmateLibrary::setup()]+0x28): undefined reference to `calculate_max_brightness_for_power_mW(unsig
```

I found also that I had to add `COMPONENT_SRCDIRS` for this to work. Removing either of these lines causes compilation to fail. 

If there is a simpler fix, I'd love to know what it is, but this made everything work for me!

### CODE REVIEW

**Comment by elliottkember** [comment]
This fixes  https://github.com/FastLED/FastLED/issues/1118

**Comment by uberjay** [comment]
Thanks for the PR -- this looks like it'll take care of the esp32, but I'm worried it'll not play nice with the esp8266. (since you've got a couple esp/32 specific paths in there now.)

**Comment by elliottkember** [comment]
@uberjay Good point. In fact it won't work for ESP8266 anyway because there is a `src/platforms/esp/8266` directory that we need to add.

I think the answer is to wrap the code in each file with `#ifdef ESP32` and `#ifdef ESP8266` blocks?

**Comment by uberjay** [comment]
Looking at this a bit further, it seems like ESP-IDF only targets the esp32, so maybe there's no issue and your PR is correct?

**Comment by elliottkember** [comment]
> Looking at this a bit further, it seems like ESP-IDF only targets the esp32, so maybe there's no issue and your PR is correct?

Yes I think you're right. It seems there is a plan to use ESP-IDF for ESP8266, but no set timeline for this.

**Comment by uberjay** [comment]
Before the repo reorg, the include path was ".", because all of the files were in the top-level directory. But the esp platform support includes where still in `platforms/esp/{32,8266}`. How did it work before? Is it possible that you don't need to add the src/platforms/esp/32 path to the `COMPONENT_ADD_INCLUDEDIRS`, but _do_ need it for `COMPONENT_SRCDIRS`? Before @samguyer reworked the esp32 support, there were only headers in the two esp platform directories. Perhaps I should try building this with ESP-IDF myself.

**Comment by uberjay** [comment]
Thanks for the PR! If it turns out this needs be tweaked some more, we can fix it up later.
