### ISSUE TITLE
linux_native red after #2594: meson test discovery picks up tests/fbuild_qemu_smoke/src/main.cpp

### ISSUE THREAD

**Issue by zackees** [FastLED/FastLED#2599]
## Symptom

`linux_native` host C++ tests fail on master since #2594 merged:

```
tests/fbuild_qemu_smoke/src/main.cpp:19:10: fatal error: 'Arduino.h' file not found
FAILED: tests/main.so.p/fbuild_qemu_smoke_src_main.cpp.o
```

Reproducible: most recent `linux_native` workflow on master (run 26688913311).

## Root cause

#2594 renamed `tests/fbuild_qemu_smoke/src/main.ino` → `main.cpp` to satisfy `arduino-lint-action`'s rule LD003 ("Sketch(es) found outside examples and extras folders"). That fixed `Arduino Library Lint`, but meson's test-file discovery (`tests/discover_tests.py` → `tests/test_config.py::EXCLUDED_TEST_DIRS`) walks `tests/` looking for `.cpp` files — the `.ino` was invisible to that walker. After the rename, meson tries to compile `main.cpp` as a host unit test against the native toolchain, which doesn't have `<Arduino.h>`.

The fixture is intentionally a **standalone PIO project** (driven by `ci/tests/test_fbuild_qemu.py` via `pio run`), not a host unit test. It must not be picked up by `linux_native`.

## Fix

One-line addition to `tests/test_config.py::EXCLUDED_TEST_DIRS`:

```python
TESTS_DIR / "fbuild_qemu_smoke",
```

with an explanatory comment crossing this back to #2593 / #2594. The fixture continues to be driven correctly by `ci/tests/test_fbuild_qemu.py`.

## Test plan

- [x] `bash lint` clean.
- [x] `bash test fastled_core --cpp --clean` — host smoke test compiles + passes (35 s clean, includes a full meson reconfigure that re-runs discovery).
- [ ] CI: `linux_native` workflow should go green again.
- [ ] `ci/tests/test_fbuild_qemu.py` continues to work (path-based).

## Notes

This is a regression my own #2594 introduced — apologies for the churn. The two cleanup options were (a) exclude the fixture from meson's walk (this PR), or (b) move it out of `tests/` entirely. (a) is one line and preserves the existing file layout that `test_fbuild_qemu.py` already knows.

---

Filed during a coordinated CI-green sweep; fix PR landing immediately.
