### ISSUE TITLE
Teensy mObjectFLED not initialized

### ISSUE THREAD

**Issue by clinder** [FastLED/FastLED#2185]
I'm having issues building and running on the Teensy 4.1. The first issue is that the FastLED master doesn't build in the Arduino IDE 2.3.7. I get errors like:
`\Arduino\libraries\FastLED\src/platforms/arm/teensy/semaphore_teensy.cpp.hpp:142:103: error: 'milli' is not a member of 'std'; did you mean 'fl::milli'?`
When I address these errors by replacing std::??? with fl::??? I get different errors:
`\Arduino\libraries\FastLED\src/platforms/arm/teensy/semaphore_teensy.cpp.hpp:148:104: error: 'steady_clock' is not a member of 'std::chrono'`
I resolved these by commenting out the last tow lines in semaphore_teensy.cpp.hpp. This allows the code to build and run, but no LEDs light and I get errors on repeat in the log (see below).

I'm on FastLED master synced to to commit e65d9c5 from 2026-02-19. I'm running Blink. The strip is 5v WS2812 RGB which is known to work.

```
22:28:51.652 -> ✓ Blink setup complete - starting blink loop
22:28:51.652 -> 
22:28:51.901 -> src/platforms/arm/teensy/teensy4_common/clockless_objectfled.cpp.hpp(256): WARN: ObjectFLEDGroupBase::writePixels: mObjectFLED not initialized
22:28:51.998 -> src/platforms/arm/teensy/teensy4_common/clockless_objectfled.cpp.hpp(256): WARN: ObjectFLEDGroupBase::writePixels: mObjectFLED not initialized
22:28:52.505 -> src/platforms/arm/teensy/teensy4_common/clockless_objectfled.cpp.hpp(256): WARN: ObjectFLEDGroupBase::writePixels: mObjectFLED not initialized
22:28:52.598 -> src/platforms/arm/teensy/teensy4_common/clockless_objectfled.cpp.hpp(256): WARN: ObjectFLEDGroupBase::writePixels: mObjectFLED not initialized
22:28:53.092 -> src/platforms/arm/teensy/teensy4_common/clockless_objectfled.cpp.hpp(256): WARN: ObjectFLEDGroupBase::writePixels: mObjectFLED not initialized
22:28:53.216 -> src/platforms/arm/teensy/teensy4_common/clockless_objectfled.cpp.hpp(256): WARN: ObjectFLEDGroupBase::writePixels: mObjectFLED not initialized
22:28:53.708 -> src/platforms/arm/teensy/teensy4_common/clockless_objectfled.cpp.hpp(256): WARN: ObjectFLEDGroupBase::writePixels: mObjectFLED not initialized
```
