### ISSUE TITLE
ESP-IDF 6.0 compatibility: PERIPH_I2S1_MODULE removed

### ISSUE THREAD

**Issue by swoboda1337** [FastLED/FastLED#2200]
## Description

FastLED fails to compile on ESP-IDF 6.0 due to `PERIPH_I2S1_MODULE` being removed from `soc/periph_defs.h`.

```
i2s_esp32dev.cpp:360:30: error: 'PERIPH_I2S1_MODULE' was not declared in this scope
  360 |         periph_module_enable(PERIPH_I2S1_MODULE);
```

In IDF 6.0, only `PERIPH_I2S0_MODULE` remains in the shared periph module enum. The I2S1 peripheral clock is now managed via the LL (low-level) API.

## Affected file

`src/platforms/esp/32/drivers/i2s/i2s_esp32dev.cpp.hpp` (master)

## Suggested fix

FastLED already uses `ESP_IDF_VERSION` guards (e.g. `ESP_IDF_VERSION_5_OR_HIGHER` in `esp_version.h`). Adding an `ESP_IDF_VERSION_6_OR_HIGHER` predicate and guarding the I2S peripheral enable would be consistent:

In `esp_version.h`:
```cpp
#ifndef ESP_IDF_VERSION_6_OR_HIGHER
#define ESP_IDF_VERSION_6_OR_HIGHER (ESP_IDF_VERSION >= ESP_IDF_VERSION_VAL(6, 0, 0))
#endif
```

Then in `i2s_esp32dev.cpp.hpp`:
```cpp
#if ESP_IDF_VERSION_6_OR_HIGHER
#include "hal/i2s_ll.h"
#endif
```

```cpp
if (i2s_device == 0) {
    i2s = &I2S0;
#if ESP_IDF_VERSION_6_OR_HIGHER
    PERIPH_RCC_ATOMIC() {
        i2s_ll_enable_bus_clock(0, true);
        i2s_ll_reset_register(0);
    }
#else
    periph_module_enable(PERIPH_I2S0_MODULE);
#endif
    interruptSource = ETS_I2S0_INTR_SOURCE;
    i2s_base_pin_index = I2S0O_DATA_OUT0_IDX;
} else {
    i2s = &I2S1;
#if ESP_IDF_VERSION_6_OR_HIGHER
    PERIPH_RCC_ATOMIC() {
        i2s_ll_enable_bus_clock(1, true);
        i2s_ll_reset_register(1);
    }
#else
    periph_module_enable(PERIPH_I2S1_MODULE);
#endif
    interruptSource = ETS_I2S1_INTR_SOURCE;
    i2s_base_pin_index = I2S1O_DATA_OUT0_IDX;
}
```

## Environment

- ESP-IDF 6.0.0-rc1
- ESP32 (original) target
- FastLED 3.9.16 / 3.10.3

**Comment by swoboda1337** [comment]
> cool i'll get this in

Thanks! When could we see a release? We are hoping to switch next month and will have to disable fastled on esp32 if IDF6 support is not there.

**Comment by zackees** [comment]
can you elaborate?

**Comment by swoboda1337** [comment]
When will an IDF 6 compatible version of fastled be released?
