### ISSUE TITLE
FastLED 3.10.3: Compile error on Arduino IDE 2.3.6

### ISSUE THREAD

**Issue by PaTuxGit** [FastLED/FastLED#2090]
Updated to FastLED 3.10.3, and now my project fails compiling (error in FastLED rbtree module):

from /home/pascal/Projects/HOBBY/Elektronik/ArduinoSketches/libraries/FastLED/src/controller.h:9,
                 from /home/pascal/Projects/HOBBY/Elektronik/ArduinoSketches/libraries/FastLED/src/FastLED.h:82,
                 from /home/pascal/Projects/HOBBY/Elektronik/ArduinoSketches/NeoPixelController/LedAnimationBase.ino:9:
/home/pascal/Projects/HOBBY/Elektronik/ArduinoSketches/libraries/FastLED/src/fl/initializer_list.h:53:24: note: candidate: template<class T> constexpr const T* fl::end(fl::initializer_list<T>)
     constexpr const T* end(initializer_list<T> il) {
                        ^~~
/home/pascal/Projects/HOBBY/Elektronik/ArduinoSketches/libraries/FastLED/src/fl/initializer_list.h:53:24: note:   template argument deduction/substitution failed:
In file included from /home/pascal/Projects/HOBBY/Elektronik/ArduinoSketches/libraries/FastLED/src/fl/map.h:14:0,
                 from /home/pascal/Projects/HOBBY/Elektronik/ArduinoSketches/libraries/FastLED/src/fl/screenmap.h:9,
                 from /home/pascal/Projects/HOBBY/Elektronik/ArduinoSketches/libraries/FastLED/src/fl/engine_events.h:4,
                 from /home/pascal/Projects/HOBBY/Elektronik/ArduinoSketches/libraries/FastLED/src/cled_controller.h:17,
                 from /home/pascal/Projects/HOBBY/Elektronik/ArduinoSketches/libraries/FastLED/src/cpixel_ledcontroller.h:15,
                 from /home/pascal/Projects/HOBBY/Elektronik/ArduinoSketches/libraries/FastLED/src/controller.h:9,
                 from /home/pascal/Projects/HOBBY/Elektronik/ArduinoSketches/libraries/FastLED/src/FastLED.h:82,
                 from /home/pascal/Projects/HOBBY/Elektronik/ArduinoSketches/NeoPixelController/LedAnimationBase.ino:9:
/home/pascal/Projects/HOBBY/Elektronik/ArduinoSketches/libraries/FastLED/src/fl/rbtree.h:531:42: note:   candidate expects 1 argument, 0 provided
         if (root_ == nullptr) return end();
                                          ^
/home/pascal/Projects/HOBBY/Elektronik/ArduinoSketches/libraries/FastLED/src/fl/rbtree.h:532:39: error: 'root_' was not declared in this scope
         return const_iterator(minimum(root_), this);
                                       ^~~~~
/home/pascal/Projects/HOBBY/Elektronik/ArduinoSketches/libraries/FastLED/src/fl/rbtree.h:532:31: error: 'minimum' was not declared in this scope
         return const_iterator(minimum(root_), this);
                               ^~~~~~~
/home/pascal/Projects/HOBBY/Elektronik/ArduinoSketches/libraries/FastLED/src/fl/rbtree.h:532:47: error: invalid use of 'this' in non-member function
         return const_iterator(minimum(root_), this);
                                               ^~~~
...

Attached the complete compile log:
[errorlog.txt](https://github.com/user-attachments/files/22533925/errorlog.txt)

Target: Arduino Nano Every

**Comment by PaTuxGit** [comment]
Similar problem on FastLED 3.10.2 : [errorlog.txt](https://github.com/user-attachments/files/22534035/errorlog.txt)

Compiles fine on FastLED 3.10.1: [buildlog.txt](https://github.com/user-attachments/files/22534064/buildlog.txt)

REMARK:
Project compiled with FastLED 3.10.1 not tested on target

**Comment by zackees** [comment]
Thanks for your bug report. Please download the library to get the updates, or set your Platfromio.ini file to use the master branch or the latest commit to get the changes into your project.

Please re-open the bug if your issue isn't fixed.

**Comment by zackees** [comment]
should be fixed now
