### ISSUE TITLE
ESP32-C3-zero: Won't compile with version 3.9.12

### ISSUE THREAD

**Issue by Rob190** [FastLED/FastLED#1872]
Using, esp32-c3-devkitc-02, I get a compile error: 

`.pio/libdeps/esp32-c3-devkitc-02/FastLED/src/platforms/esp/32/clock_cycles.h:9:35: error: 'esp_cpu_get_cycle_count' was not declared in this scope`

Compiles ok with 3.9.2

**Comment by Ben212** [comment]
Got the same problem using esp32-c3-devkitm-1 and FastLED 3.9.12 (latest) and 3.9.11
error: *** [.pio/build/esp32-c3-devkitm-1/lib2b9/FastLED/platforms/esp/32/rmt_4/idf4_rmt_impl.cpp.o] Error 1
*** [.pio/build/esp32-c3-devkitm-1/lib2b9/FastLED/platforms/esp/32/rmt_4/idf4_rmt.cpp.o] Error 1
 
but work if I use 3.9.10

**Comment by thomergil** [comment]
Same as @Rob190; indeed still compiles with 3.9.10.
